[package]
name = "eccer"
version = "0.1.0"
authors = ["Felix Stegmaier <stegmaier.felix@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.35"
deadpool = "0.6.0"
env_logger = "0.8.2"
etcd-client = "0.5.4"
log = "0.4.11"
nats = "0.8.6"
thiserror = "1.0.22"
tide = "0.15.0"
tokio = { version = "0.2.23", features = ["full"] }
serde = "1.0.118"
serde_json = "1.0.60"
structopt = "0.3.21"
url = "2.2.0"