[package]
name = "eccer"
version = "0.1.1"
authors = ["Felix Stegmaier <stegmaier.felix@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
# async-std = { version = "1", features = ["attributes"] }
# deadpool = "0.9.5"
env_logger = "0.9.1"
etcd-client = "0.10.2"
log = "0.4.17"
nats = "0.23.0"
thiserror = "1.0.37"
# TODO: replace tide with tokio compatible http server instead of async-std
tide = "0.16.0"
tokio = { version = "1", features = ["full"] }
serde = "1"
serde_json = "1"
structopt = "0.3.26"
url = "2.3.1"