[package]
name = "eccer"
version = "0.1.4"
authors = ["Felix Stegmaier <stegmaier.felix@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-stream = "0.3.6"
# TODO: update axum
axum = "0.6.18"
axum-prometheus = "0.3.3"
chrono = { version = "0.4.40", features = ["clock", "serde"] }
clap = { version = "4.5.35", features = ["derive", "env"] }
etcd-client = "0.14.1"
futures-core = "0.3.31"
futures-util = "0.3.31"
# TODO: update hyer to v1 SEE https://hyper.rs/guides/1/upgrading/
hyper = { version = "0.14.26", features = ["full"] }
nats = "0.25.0"
reqwest = "0.12.15"
serde = "1"
serde_json = "1"
# TODO: update to v2
thiserror = "1"
tokio = { version = "1", features = ["full"] }
# TODO: update tower
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
url = { version = "2", features = ["serde"] }
